### use balance
POST  http://localhost:8080/transaction/use
Content-Type: application/json

{
    "userId" : 1,
    "accountNumber" : "1000000000",
    "amount" : 12345
}

### cancel balance
POST  http://localhost:8080/transaction/cancel
Content-Type: application/json

{
    "transactionId" : "9",
    "accountNumber" : "1000000001",
    "amount" : 10000
}